[package]
name = "SOADeathCounter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
dolphin-memory = "0.2.3"
image = "0.25.5"
indicatif = "0.17.11"
tokio = { version = "1.43.0", features = ["full"] }
viuer = "0.9.1"
